# -*- coding: utf-8 -*-
"""Phase 1: curriculum units (PLAN 付録 A を JSON 化するための元データ).

JP: MEXT 2017 改訂（中学校）/ 2018 改訂（高等学校）の科目・単元・小項目。
US: Traditional / Integrated / AP / College の 4 系統。
"""

MEXT_HS = {"type": "mext-translation", "doc": "高等学校学習指導要領（平成30年告示）英訳版（仮訳）"}
MEXT_JHS = {"type": "mext-translation", "doc": "中学校学習指導要領（平成29年告示）英訳版（仮訳）"}
CCSS = {"type": "reference", "title": "Common Core State Standards for Mathematics, Appendix A: Designing High School Mathematics Courses"}
AP_CALC = {"type": "reference", "title": "AP Calculus AB and BC Course and Exam Description (College Board)"}
AP_STAT = {"type": "reference", "title": "AP Statistics Course and Exam Description (College Board)"}
OS_PREALG = {"type": "textbook", "title": "OpenStax Prealgebra 2e"}
OS_ALG = {"type": "textbook", "title": "OpenStax Algebra and Trigonometry 2e"}
OS_PRECALC = {"type": "textbook", "title": "OpenStax Precalculus 2e"}
OS_CALC1 = {"type": "textbook", "title": "OpenStax Calculus Volume 1"}
OS_CALC2 = {"type": "textbook", "title": "OpenStax Calculus Volume 2"}
OS_CALC3 = {"type": "textbook", "title": "OpenStax Calculus Volume 3"}
OS_STAT = {"type": "textbook", "title": "OpenStax Introductory Statistics 2e"}
LAY = {"type": "textbook", "title": "Lay, Lay & McDonald, Linear Algebra and Its Applications (chapter structure only)"}
ROSEN = {"type": "textbook", "title": "Rosen, Discrete Mathematics and Its Applications (chapter structure only)"}
GEO = {"type": "textbook", "title": "Typical US high-school Geometry sequence (e.g. Big Ideas Geometry), chapter structure only"}

# ----------------------------------------------------------------------------- JP
# (id, subject, unit, topics, us_equivalents, levels_us_for_ledger, domain)
# us_equivalents: (course, coverage, note?)  course は level.us の enum と一致させる
JP = [
    # ---------------- 中1
    ("jp-chuugaku-1-seifu-no-suu", "中1", "正の数と負の数",
     ["正の数・負の数", "数直線と絶対値", "加法と減法", "乗法と除法", "累乗", "素因数分解", "数の集合と四則"],
     [("Pre-Algebra", "full"), ("Integrated Math 1", "some", "整数の四則は Math 7 で終えている前提")],
     ["Pre-Algebra"], "arithmetic"),
    ("jp-chuugaku-1-moji-to-shiki", "中1", "文字と式",
     ["文字を用いた式", "式の値", "一次式の計算", "関係を表す式（等式・不等式）"],
     [("Pre-Algebra", "full"), ("Algebra 1", "some")],
     ["Pre-Algebra", "Algebra 1"], "algebra"),
    ("jp-chuugaku-1-ichiji-houteishiki", "中1", "一次方程式",
     ["方程式とその解", "等式の性質", "一次方程式の解き方", "比例式", "一次方程式の利用"],
     [("Pre-Algebra", "most"), ("Algebra 1", "most", "多段階の一次方程式は Algebra 1 の最初の単元"), ("Integrated Math 1", "most")],
     ["Pre-Algebra", "Algebra 1"], "algebra"),
    ("jp-chuugaku-1-hirei-hanpirei", "中1", "比例と反比例",
     ["関数", "比例", "反比例", "座標", "比例・反比例のグラフ", "比例・反比例の利用"],
     [("Pre-Algebra", "most", "direct / inverse variation として"), ("Algebra 1", "some")],
     ["Pre-Algebra", "Algebra 1"], "functions"),
    ("jp-chuugaku-1-heimen-zukei", "中1", "平面図形",
     ["直線と角", "図形の移動（平行移動・回転移動・対称移動）", "基本の作図", "円とおうぎ形", "おうぎ形の弧の長さと面積"],
     [("Pre-Algebra", "some"), ("Geometry", "most", "作図と移動は米国では Geometry"), ("Integrated Math 1", "most")],
     ["Pre-Algebra", "Geometry"], "geometry"),
    ("jp-chuugaku-1-kuukan-zukei", "中1", "空間図形",
     ["いろいろな立体", "直線や平面の位置関係", "立体の表し方（投影図・展開図）", "立体の表面積と体積", "球の表面積と体積"],
     [("Pre-Algebra", "most"), ("Geometry", "some", "表面積・体積は Geometry の終盤")],
     ["Pre-Algebra", "Geometry"], "geometry"),
    ("jp-chuugaku-1-data-no-katsuyou", "中1", "データの活用",
     ["度数分布表とヒストグラム", "相対度数・累積度数", "代表値と範囲", "統計的確率（多数回の試行）"],
     [("Pre-Algebra", "most"), ("Algebra 1", "some")],
     ["Pre-Algebra"], "statistics"),
    # ---------------- 中2
    ("jp-chuugaku-2-shiki-no-keisan", "中2", "式の計算",
     ["単項式と多項式", "多項式の加法・減法", "単項式の乗法・除法", "文字式の利用（整数の性質の説明）", "等式の変形"],
     [("Algebra 1", "most"), ("Integrated Math 1", "most")],
     ["Algebra 1", "Integrated Math 1"], "algebra"),
    ("jp-chuugaku-2-renritsu-houteishiki", "中2", "連立方程式",
     ["連立二元一次方程式", "加減法", "代入法", "連立方程式の利用"],
     [("Algebra 1", "full"), ("Integrated Math 1", "full")],
     ["Algebra 1", "Integrated Math 1"], "algebra"),
    ("jp-chuugaku-2-ichiji-kansuu", "中2", "一次関数",
     ["一次関数", "一次関数の値の変化", "一次関数のグラフ", "一次関数と方程式", "一次関数の利用"],
     [("Algebra 1", "full"), ("Integrated Math 1", "full")],
     ["Algebra 1", "Integrated Math 1"], "functions"),
    ("jp-chuugaku-2-heikou-to-goudou", "中2", "平行と合同",
     ["平行線と角（対頂角・同位角・錯角）", "多角形の内角と外角", "三角形の合同", "合同条件", "証明のしくみ"],
     [("Geometry", "full"), ("Integrated Math 1", "most")],
     ["Geometry", "Integrated Math 1"], "geometry"),
    ("jp-chuugaku-2-sankakkei-to-shikakkei", "中2", "三角形と四角形",
     ["二等辺三角形", "直角三角形の合同", "平行四辺形", "特別な平行四辺形", "平行線と面積"],
     [("Geometry", "full"), ("Integrated Math 2", "some")],
     ["Geometry"], "geometry"),
    ("jp-chuugaku-2-data-no-katsuyou", "中2", "データの活用",
     ["四分位数", "四分位範囲", "箱ひげ図", "データの傾向の比較"],
     [("Algebra 1", "most"), ("AP Statistics", "some")],
     ["Algebra 1"], "statistics"),
    ("jp-chuugaku-2-kakuritsu", "中2", "確率",
     ["同様に確からしいこと", "確率の求め方（樹形図・表）", "いろいろな確率"],
     [("Pre-Algebra", "most"), ("Geometry", "some", "米国では Geometry の末尾に確率を置く教科書がある"), ("Integrated Math 2", "most")],
     ["Pre-Algebra", "Integrated Math 2"], "probability"),
    # ---------------- 中3
    ("jp-chuugaku-3-tenkai-insuubunkai", "中3", "式の展開と因数分解",
     ["多項式の乗法", "乗法公式", "因数分解", "式の計算の利用"],
     [("Algebra 1", "full"), ("Integrated Math 1", "most"), ("Integrated Math 2", "some")],
     ["Algebra 1", "Integrated Math 1"], "algebra"),
    ("jp-chuugaku-3-heihoukon", "中3", "平方根",
     ["平方根", "根号を含む式の計算", "有理数と無理数", "近似値と有効数字"],
     [("Algebra 1", "most"), ("Integrated Math 2", "most")],
     ["Algebra 1", "Integrated Math 2"], "arithmetic"),
    ("jp-chuugaku-3-niji-houteishiki", "中3", "二次方程式",
     ["二次方程式とその解", "因数分解による解法", "平方根の考えによる解法", "解の公式", "二次方程式の利用"],
     [("Algebra 1", "full"), ("Integrated Math 2", "full")],
     ["Algebra 1", "Integrated Math 2"], "algebra"),
    ("jp-chuugaku-3-kansuu-y-ax2", "中3", "関数 y=ax²",
     ["関数 y=ax²", "y=ax² のグラフ", "y=ax² の値の変化", "いろいろな事象と関数"],
     [("Algebra 1", "full"), ("Integrated Math 2", "full")],
     ["Algebra 1", "Integrated Math 2"], "functions"),
    ("jp-chuugaku-3-souji", "中3", "相似な図形",
     ["相似な図形", "三角形の相似条件", "平行線と線分の比", "中点連結定理", "相似な図形の面積比・体積比", "相似の利用"],
     [("Geometry", "full"), ("Integrated Math 2", "full")],
     ["Geometry", "Integrated Math 2"], "geometry"),
    ("jp-chuugaku-3-en", "中3", "円",
     ["円周角の定理", "円周角の定理の逆", "円周角の定理の利用"],
     [("Geometry", "most"), ("Integrated Math 2", "most")],
     ["Geometry", "Integrated Math 2"], "geometry"),
    ("jp-chuugaku-3-sanpeihou", "中3", "三平方の定理",
     ["三平方の定理", "三平方の定理の逆", "平面図形への利用", "空間図形への利用"],
     [("Geometry", "full"), ("Pre-Algebra", "some"), ("Integrated Math 2", "full")],
     ["Geometry", "Integrated Math 2"], "geometry"),
    ("jp-chuugaku-3-hyouhon-chousa", "中3", "標本調査",
     ["全数調査と標本調査", "無作為抽出", "標本調査の利用"],
     [("Algebra 1", "some"), ("AP Statistics", "some"), ("Intro Statistics", "some")],
     ["Algebra 1"], "statistics"),
    # ---------------- 数学I
    ("jp-suugaku-1-kazu-to-shiki", "数学I", "数と式",
     ["整式の加法・減法・乗法", "因数分解", "実数", "絶対値", "平方根と有理化", "一次不等式", "絶対値を含む方程式・不等式"],
     [("Algebra 1", "most"), ("Algebra 2", "some"), ("Integrated Math 2", "most")],
     ["Algebra 1", "Algebra 2"], "algebra"),
    ("jp-suugaku-1-shuugou-to-meidai", "数学I", "集合と命題",
     ["集合", "集合の演算", "命題と条件", "必要条件・十分条件", "逆・裏・対偶", "背理法"],
     [("Geometry", "some", "条件文・逆・対偶は Geometry の証明単元"), ("Discrete Math", "most", "集合と論理は大学の Discrete Math が本格的")],
     ["Geometry", "Discrete Math"], "logic"),
    ("jp-suugaku-1-niji-kansuu", "数学I", "二次関数",
     ["関数とグラフ", "二次関数のグラフ", "二次関数の最大・最小", "二次関数の決定", "二次方程式", "二次不等式", "グラフと x 軸の位置関係"],
     [("Algebra 1", "most"), ("Algebra 2", "most"), ("Integrated Math 2", "most")],
     ["Algebra 1", "Algebra 2"], "functions"),
    ("jp-suugaku-1-zukei-to-keiryou", "数学I", "図形と計量",
     ["三角比", "三角比の相互関係", "三角比の拡張（鈍角）", "正弦定理", "余弦定理", "三角形の面積", "空間図形への応用"],
     [("Geometry", "most", "直角三角形の三角比と Law of Sines / Cosines"), ("Algebra 2", "some"), ("Precalculus", "some", "米国では sec / csc / cot と単位円も同時に入る")],
     ["Geometry", "Precalculus"], "trigonometry"),
    ("jp-suugaku-1-data-no-bunseki", "数学I", "データの分析",
     ["データの整理", "代表値", "四分位数と箱ひげ図", "分散と標準偏差", "散布図と相関係数", "仮説検定の考え方"],
     [("Algebra 1", "most"), ("Algebra 2", "some"), ("AP Statistics", "some"), ("Intro Statistics", "some")],
     ["Algebra 1", "AP Statistics"], "statistics"),
    # ---------------- 数学A
    ("jp-suugaku-a-baai-no-kazu-to-kakuritsu", "数学A", "場合の数と確率",
     ["集合の要素の個数", "場合の数", "順列", "組合せ", "事象と確率", "独立な試行と確率", "反復試行", "条件付き確率", "期待値"],
     [("Algebra 2", "most"), ("Precalculus", "some"), ("AP Statistics", "some"), ("Discrete Math", "most")],
     ["Algebra 2", "Discrete Math"], "combinatorics"),
    ("jp-suugaku-a-zukei-no-seishitsu", "数学A", "図形の性質",
     ["三角形の性質（内分・外分、五心）", "チェバの定理・メネラウスの定理", "円の性質（内接四角形・接弦定理・方べきの定理）", "2 円の位置関係", "作図", "空間図形（直線と平面、多面体）"],
     [("Geometry", "most", "チェバ・メネラウス・方べきの定理は米国では扱いが薄い"), ("Integrated Math 2", "some")],
     ["Geometry"], "geometry"),
    ("jp-suugaku-a-suugaku-to-ningen-no-katsudou", "数学A", "数学と人間の活動",
     ["約数と倍数", "ユークリッドの互除法", "一次不定方程式", "n 進法", "合同式", "座標と経路", "ゲームやパズルの中の数学"],
     [("Discrete Math", "most", "整数論の基礎は大学の Discrete Math / Number Theory"), ("Pre-Algebra", "some", "約数・倍数・素因数分解のみ")],
     ["Discrete Math"], "number-theory"),
    # ---------------- 数学II
    ("jp-suugaku-2-shiki-to-shoumei", "数学II", "式と証明",
     ["整式の除法", "分数式", "恒等式", "等式の証明", "不等式の証明", "二項定理", "相加平均・相乗平均"],
     [("Algebra 2", "most"), ("Precalculus", "some", "二項定理は Precalculus")],
     ["Algebra 2", "Precalculus"], "algebra"),
    ("jp-suugaku-2-fukusosuu-to-houteishiki", "数学II", "複素数と方程式",
     ["複素数", "二次方程式の解と判別式", "解と係数の関係", "剰余の定理・因数定理", "高次方程式"],
     [("Algebra 2", "full"), ("Integrated Math 3", "most")],
     ["Algebra 2", "Integrated Math 3"], "algebra"),
    ("jp-suugaku-2-zukei-to-houteishiki", "数学II", "図形と方程式",
     ["点と座標", "直線の方程式", "円の方程式", "円と直線", "軌跡と方程式", "不等式の表す領域"],
     [("Geometry", "some", "座標幾何の基礎"), ("Algebra 2", "some"), ("Precalculus", "most", "円の方程式・線形計画法・軌跡")],
     ["Geometry", "Precalculus"], "geometry"),
    ("jp-suugaku-2-sankaku-kansuu", "数学II", "三角関数",
     ["一般角と弧度法", "三角関数", "三角関数の性質とグラフ", "三角関数の加法定理", "2 倍角・半角の公式", "三角関数の合成"],
     [("Algebra 2", "some"), ("Precalculus", "full")],
     ["Algebra 2", "Precalculus"], "trigonometry"),
    ("jp-suugaku-2-shisuu-taisuu", "数学II", "指数関数と対数関数",
     ["指数の拡張", "指数関数", "対数とその性質", "対数関数", "常用対数"],
     [("Algebra 2", "full"), ("Precalculus", "full"), ("Integrated Math 3", "most")],
     ["Algebra 2", "Precalculus"], "functions"),
    ("jp-suugaku-2-bibun-no-kangae", "数学II", "微分の考え",
     ["微分係数", "導関数", "接線", "関数の増減と極大・極小", "最大・最小", "方程式・不等式への応用"],
     [("AP Calculus AB", "some", "多項式の微分のみ"), ("Calculus I", "some"), ("Precalculus", "some", "極限の導入のみ")],
     ["AP Calculus AB", "Calculus I"], "calculus"),
    ("jp-suugaku-2-sekibun-no-kangae", "数学II", "積分の考え",
     ["不定積分", "定積分", "面積"],
     [("AP Calculus AB", "some", "多項式の積分と面積のみ"), ("Calculus I", "some")],
     ["AP Calculus AB", "Calculus I"], "calculus"),
    # ---------------- 数学B
    ("jp-suugaku-b-suuretsu", "数学B", "数列",
     ["等差数列", "等比数列", "いろいろな数列と和（Σ）", "階差数列", "漸化式", "数学的帰納法"],
     [("Algebra 2", "most"), ("Precalculus", "most", "数学的帰納法は Precalculus"), ("Integrated Math 3", "some")],
     ["Algebra 2", "Precalculus"], "sequences"),
    ("jp-suugaku-b-toukei-teki-na-suisoku", "数学B", "統計的な推測",
     ["確率変数と確率分布", "二項分布", "正規分布", "母集団と標本", "推定", "仮説検定"],
     [("AP Statistics", "most"), ("Intro Statistics", "most"), ("Algebra 2", "some")],
     ["AP Statistics", "Intro Statistics"], "statistics"),
    ("jp-suugaku-b-suugaku-to-shakai-seikatsu", "数学B", "数学と社会生活",
     ["数学的モデル化", "データの傾向の分析（回帰・移動平均）", "近似と補間"],
     [("Algebra 2", "some"), ("AP Statistics", "some")],
     ["Algebra 2"], "statistics"),
    # ---------------- 数学III
    ("jp-suugaku-3-kyokugen", "数学III", "極限",
     ["分数関数・無理関数", "逆関数・合成関数", "数列の極限", "無限級数", "関数の極限", "関数の連続性"],
     [("Precalculus", "some", "分数関数・逆関数・合成関数・極限の導入"), ("AP Calculus AB", "most"), ("AP Calculus BC", "most", "無限級数は BC"), ("Calculus I", "most"), ("Calculus II", "some", "無限級数")],
     ["AP Calculus AB", "Calculus I"], "analysis"),
    ("jp-suugaku-3-bibun", "数学III", "微分法",
     ["微分法（積・商・合成関数）", "いろいろな関数の導関数", "高次導関数・陰関数・媒介変数", "接線と法線", "平均値の定理", "関数の増減とグラフの凹凸", "速度・加速度、近似式"],
     [("AP Calculus AB", "full"), ("AP Calculus BC", "full"), ("Calculus I", "full")],
     ["AP Calculus AB", "Calculus I"], "calculus"),
    ("jp-suugaku-3-sekibun", "数学III", "積分法",
     ["不定積分", "置換積分法", "部分積分法", "定積分", "区分求積法", "面積", "体積", "曲線の長さ", "速度と道のり"],
     [("AP Calculus AB", "most", "置換・体積・面積"), ("AP Calculus BC", "most", "部分積分・部分分数は BC"), ("Calculus I", "some"), ("Calculus II", "most", "数IIIの積分は Calc I 後半〜Calc II 前半。級数・Taylor は日本の高校範囲外")],
     ["AP Calculus BC", "Calculus II"], "calculus"),
    # ---------------- 数学C
    ("jp-suugaku-c-vector", "数学C", "ベクトル",
     ["平面上のベクトル", "ベクトルの演算", "ベクトルの成分", "ベクトルの内積", "位置ベクトル", "ベクトル方程式", "空間のベクトル"],
     [("Precalculus", "most", "平面ベクトルと内積"), ("Calculus III", "some", "空間ベクトル"), ("Linear Algebra", "some")],
     ["Precalculus", "Calculus III"], "vectors"),
    ("jp-suugaku-c-kyokusen-to-fukuso-heimen", "数学C", "平面上の曲線と複素数平面",
     ["二次曲線（放物線・楕円・双曲線）", "媒介変数表示", "極座標と極方程式", "複素数平面", "極形式とド・モアブルの定理", "複素数と図形"],
     [("Precalculus", "most", "円錐曲線・極座標・複素数の極形式"), ("Algebra 2", "some", "複素数の演算"), ("AP Calculus BC", "some", "媒介変数・極座標の微積")],
     ["Precalculus"], "complex-numbers"),
    ("jp-suugaku-c-hyougen-no-kufuu", "数学C", "数学的な表現の工夫",
     ["行列", "離散グラフ", "統計グラフ", "データの表現"],
     [("Precalculus", "some", "行列の基礎"), ("Linear Algebra", "some"), ("Discrete Math", "some", "グラフ")],
     ["Precalculus", "Linear Algebra"], "linear-algebra"),
]

# ----------------------------------------------------------------------------- US
# (id, track, subject, unit, topics, jp_equivalents, domain, sources)
# jp_equivalents: ("<科目> <単元>", coverage, note?)。科目・単元は JP の subject/unit と一致させる
US = [
    # ---------------- Pre-Algebra
    ("us-pre-algebra-integers", "traditional", "Pre-Algebra", "Integers and signed numbers",
     ["number line", "absolute value", "adding and subtracting integers", "multiplying and dividing integers", "order of operations", "exponents"],
     [("中1 正の数と負の数", "full")], "arithmetic", [OS_PREALG]),
    ("us-pre-algebra-rational-numbers", "traditional", "Pre-Algebra", "Fractions, decimals, and rational numbers",
     ["simplifying fractions", "operations with fractions", "decimals", "rational numbers", "square roots", "scientific notation"],
     [("小学校 分数・小数", "most", "分数の四則は日本では小学校"), ("中3 平方根", "some")], "arithmetic", [OS_PREALG]),
    ("us-pre-algebra-expressions-and-equations", "traditional", "Pre-Algebra", "Expressions and equations",
     ["variables and expressions", "evaluating expressions", "combining like terms", "distributive property", "one-step and two-step equations", "inequalities"],
     [("中1 文字と式", "full"), ("中1 一次方程式", "most")], "algebra", [OS_PREALG]),
    ("us-pre-algebra-ratios-and-percents", "traditional", "Pre-Algebra", "Ratios, proportions, and percents",
     ["ratios and rates", "unit rate", "proportions", "percent", "percent change", "simple interest"],
     [("小学校 割合", "most"), ("中1 一次方程式", "some", "比例式")], "arithmetic", [OS_PREALG]),
    ("us-pre-algebra-geometry-basics", "traditional", "Pre-Algebra", "Geometry basics and measurement",
     ["angles", "perimeter and area", "circles", "Pythagorean theorem", "surface area and volume", "unit conversion"],
     [("中1 平面図形", "some"), ("中1 空間図形", "most"), ("中3 三平方の定理", "some")], "geometry", [OS_PREALG]),
    ("us-pre-algebra-data-and-probability", "traditional", "Pre-Algebra", "Data and probability",
     ["mean, median, mode", "histograms and bar graphs", "probability of simple events", "compound events"],
     [("中1 データの活用", "most"), ("中2 確率", "most")], "statistics", [OS_PREALG]),
    # ---------------- Algebra 1
    ("us-algebra-1-linear-equations", "traditional", "Algebra 1", "Linear equations and inequalities",
     ["multi-step equations", "literal equations", "linear inequalities", "compound inequalities", "absolute value equations"],
     [("中1 一次方程式", "most"), ("数学I 数と式", "some", "一次不等式・絶対値")], "algebra", [CCSS, OS_ALG]),
    ("us-algebra-1-linear-functions", "traditional", "Algebra 1", "Linear functions and graphs",
     ["function notation", "domain and range", "slope", "slope-intercept form", "point-slope form", "standard form", "parallel and perpendicular lines", "arithmetic sequences"],
     [("中2 一次関数", "full"), ("中1 比例と反比例", "some")], "functions", [CCSS, OS_ALG]),
    ("us-algebra-1-systems", "traditional", "Algebra 1", "Systems of equations and inequalities",
     ["solving by graphing", "substitution", "elimination", "systems of inequalities"],
     [("中2 連立方程式", "full")], "algebra", [CCSS, OS_ALG]),
    ("us-algebra-1-exponents-and-exponential-functions", "traditional", "Algebra 1", "Exponents and exponential functions",
     ["properties of exponents", "scientific notation", "exponential growth and decay", "geometric sequences"],
     [("中1 正の数と負の数", "some", "累乗"), ("数学II 指数関数と対数関数", "some", "指数関数の導入のみ")], "functions", [CCSS, OS_ALG]),
    ("us-algebra-1-polynomials-and-factoring", "traditional", "Algebra 1", "Polynomials and factoring",
     ["adding and multiplying polynomials", "FOIL", "special products", "factoring out the GCF", "factoring trinomials", "difference of squares"],
     [("中2 式の計算", "most"), ("中3 式の展開と因数分解", "full")], "algebra", [CCSS, OS_ALG]),
    ("us-algebra-1-quadratics", "traditional", "Algebra 1", "Quadratic functions and equations",
     ["graphing parabolas", "vertex form", "solving by factoring", "completing the square", "quadratic formula", "discriminant", "transformations of functions"],
     [("中3 二次方程式", "full"), ("中3 関数 y=ax²", "full"), ("数学I 二次関数", "most")], "functions", [CCSS, OS_ALG]),
    ("us-algebra-1-radicals", "traditional", "Algebra 1", "Radical expressions",
     ["simplifying radicals", "operations with radicals", "radical equations"],
     [("中3 平方根", "full")], "arithmetic", [CCSS, OS_ALG]),
    ("us-algebra-1-statistics", "traditional", "Algebra 1", "Data and statistics",
     ["dot plots and histograms", "box plots", "measures of center and spread", "two-way tables", "scatter plots and lines of best fit"],
     [("中1 データの活用", "most"), ("中2 データの活用", "full"), ("数学I データの分析", "most")], "statistics", [CCSS]),
    # ---------------- Geometry
    ("us-geometry-foundations", "traditional", "Geometry", "Foundations of geometry",
     ["points, lines, planes", "segments and distance", "midpoint formula", "angles and angle pairs", "constructions"],
     [("中1 平面図形", "most")], "geometry", [CCSS, GEO]),
    ("us-geometry-reasoning-and-proof", "traditional", "Geometry", "Reasoning and proof",
     ["inductive and deductive reasoning", "conditional statements", "converse, inverse, contrapositive", "two-column proofs", "properties of equality and congruence"],
     [("中2 平行と合同", "some", "証明のしくみ"), ("数学I 集合と命題", "some")], "proof", [CCSS, GEO]),
    ("us-geometry-parallel-and-perpendicular", "traditional", "Geometry", "Parallel and perpendicular lines",
     ["transversals", "angle pairs formed by parallel lines", "proving lines parallel", "slopes of parallel and perpendicular lines"],
     [("中2 平行と合同", "most")], "geometry", [CCSS, GEO]),
    ("us-geometry-congruent-triangles", "traditional", "Geometry", "Congruent triangles",
     ["classifying triangles", "triangle angle sum", "SSS, SAS, ASA, AAS, HL", "CPCTC", "isosceles and equilateral triangles"],
     [("中2 平行と合同", "most"), ("中2 三角形と四角形", "most")], "geometry", [CCSS, GEO]),
    ("us-geometry-relationships-within-triangles", "traditional", "Geometry", "Relationships within triangles",
     ["midsegments", "perpendicular bisectors and angle bisectors in triangles", "points of concurrency: circumcenter, incenter, centroid, orthocenter", "medians and altitudes", "comparing sides and angles in a triangle", "triangle inequality theorem"],
     [("数学A 図形の性質", "most"), ("中3 相似な図形", "some", "中点連結定理")], "geometry", [CCSS]),  # Phase 3 記号の前の修正 1 (CK-12 Geometry 4.19-4.26)
    ("us-geometry-quadrilaterals", "traditional", "Geometry", "Quadrilaterals",
     ["interior and exterior angle sums of polygons", "properties of parallelograms", "proving a quadrilateral is a parallelogram", "rectangles, rhombuses, and squares", "trapezoids and kites", "classifying quadrilaterals"],
     [("中2 三角形と四角形", "most"), ("中2 平行と合同", "some", "多角形の内角の和・外角の和")], "geometry", [CCSS]),  # 同上 (CK-12 Geometry 5.7-5.19, 5.27-5.28)
    ("us-geometry-similarity", "traditional", "Geometry", "Similarity",
     ["dilations", "similar polygons", "AA, SAS, SSS similarity", "triangle proportionality theorem", "indirect measurement"],
     [("中3 相似な図形", "full")], "geometry", [CCSS, GEO]),
    ("us-geometry-right-triangles-and-trig", "traditional", "Geometry", "Right triangles and trigonometry",
     ["Pythagorean theorem", "special right triangles", "sine, cosine, tangent", "angles of elevation and depression", "law of sines and cosines"],
     [("中3 三平方の定理", "full"), ("数学I 図形と計量", "most")], "trigonometry", [CCSS, GEO]),
    ("us-geometry-circles", "traditional", "Geometry", "Circles",
     ["tangents", "arcs and chords", "inscribed angles", "angle relationships in circles", "segment relationships", "equation of a circle"],
     [("中3 円", "full"), ("数学A 図形の性質", "most"), ("数学II 図形と方程式", "some", "円の方程式")], "geometry", [CCSS, GEO]),
    ("us-geometry-area-and-volume", "traditional", "Geometry", "Area and volume",
     ["area of polygons", "area of regular polygons", "surface area", "volume of prisms, cylinders, pyramids, cones, spheres", "cross sections"],
     [("中1 空間図形", "full"), ("中1 平面図形", "some")], "geometry", [CCSS, GEO]),
    ("us-geometry-transformations", "traditional", "Geometry", "Transformations",
     ["translations", "reflections", "rotations", "compositions", "symmetry", "dilations"],
     [("中1 平面図形", "most", "図形の移動"), ("中3 相似な図形", "some")], "geometry", [CCSS, GEO]),
    ("us-geometry-coordinate-geometry", "traditional", "Geometry", "Coordinate geometry",
     ["distance and midpoint", "equations of lines", "coordinate proofs", "partitioning a segment"],
     [("数学II 図形と方程式", "most"), ("数学A 図形の性質", "some", "内分点")], "geometry", [CCSS, GEO]),
    # ---------------- Algebra 2
    ("us-algebra-2-functions", "traditional", "Algebra 2", "Functions and their graphs",
     ["parent functions", "transformations", "piecewise functions", "composition of functions", "inverse functions", "end behavior"],
     [("数学I 二次関数", "some"), ("数学III 極限", "some", "逆関数・合成関数")], "functions", [CCSS, OS_ALG]),
    ("us-algebra-2-quadratics-and-complex-numbers", "traditional", "Algebra 2", "Quadratic functions and complex numbers",
     ["complex numbers", "solving quadratics over the complex numbers", "discriminant", "quadratic inequalities", "systems with quadratics"],
     [("数学I 二次関数", "most"), ("数学II 複素数と方程式", "most")], "algebra", [CCSS, OS_ALG]),
    ("us-algebra-2-polynomials", "traditional", "Algebra 2", "Polynomial functions",
     ["graphing polynomials", "end behavior", "polynomial division", "remainder and factor theorems", "rational root theorem", "fundamental theorem of algebra"],
     [("数学II 式と証明", "some"), ("数学II 複素数と方程式", "most")], "algebra", [CCSS, OS_ALG]),
    ("us-algebra-2-rational-functions", "traditional", "Algebra 2", "Rational functions",
     ["simplifying rational expressions", "operations with rational expressions", "rational equations", "graphs and asymptotes", "inverse and joint variation"],
     [("数学II 式と証明", "most", "分数式"), ("数学III 極限", "some", "分数関数のグラフ")], "functions", [CCSS, OS_ALG]),
    ("us-algebra-2-radical-functions", "traditional", "Algebra 2", "Radical functions and rational exponents",
     ["nth roots", "rational exponents", "radical functions", "radical equations", "inverses"],
     [("数学II 指数関数と対数関数", "some", "指数の拡張"), ("数学III 極限", "some", "無理関数")], "functions", [CCSS, OS_ALG]),
    ("us-algebra-2-exponential-and-logarithmic", "traditional", "Algebra 2", "Exponential and logarithmic functions",
     ["exponential growth and decay", "the number e", "logarithms", "properties of logarithms", "solving exponential and logarithmic equations"],
     [("数学II 指数関数と対数関数", "full")], "functions", [CCSS, OS_ALG]),
    ("us-algebra-2-sequences-and-series", "traditional", "Algebra 2", "Sequences and series",
     ["arithmetic and geometric sequences", "recursive and explicit formulas", "series and sigma notation", "infinite geometric series"],
     [("数学B 数列", "most")], "sequences", [CCSS, OS_ALG]),
    ("us-algebra-2-trigonometry", "traditional", "Algebra 2", "Trigonometric functions",
     ["radians", "unit circle", "graphs of sine and cosine", "amplitude, period, phase shift", "inverse trig functions", "basic identities"],
     [("数学II 三角関数", "most"), ("数学I 図形と計量", "some")], "trigonometry", [CCSS, OS_ALG]),
    ("us-algebra-2-probability-and-statistics", "traditional", "Algebra 2", "Probability and statistics",
     ["permutations and combinations", "conditional probability", "binomial distribution", "normal distribution", "sampling and experiments"],
     [("数学A 場合の数と確率", "most"), ("数学B 統計的な推測", "some")], "probability", [CCSS]),
    # ---------------- Precalculus
    ("us-precalculus-functions", "traditional", "Precalculus", "Functions",
     ["function properties", "average rate of change", "difference quotient", "transformations", "inverse functions", "absolute value functions"],
     [("数学I 二次関数", "some"), ("数学II 微分の考え", "some", "平均変化率")], "functions", [OS_PRECALC]),
    ("us-precalculus-polynomial-and-rational", "traditional", "Precalculus", "Polynomial and rational functions",
     ["zeros of polynomials", "complex zeros", "rational functions and asymptotes", "partial fractions", "polynomial and rational inequalities"],
     [("数学II 複素数と方程式", "most"), ("数学II 式と証明", "some"), ("数学III 極限", "some")], "functions", [OS_PRECALC]),
    ("us-precalculus-exponential-and-logarithmic", "traditional", "Precalculus", "Exponential and logarithmic functions",
     ["exponential models", "logarithmic properties", "exponential and logarithmic equations", "logistic growth"],
     [("数学II 指数関数と対数関数", "full")], "functions", [OS_PRECALC]),
    ("us-precalculus-analytic-trigonometry", "traditional", "Precalculus", "Analytic trigonometry",
     ["verifying identities", "sum and difference formulas", "double-angle and half-angle formulas", "product-to-sum", "solving trigonometric equations", "solving triangles"],
     [("数学II 三角関数", "full"), ("数学I 図形と計量", "most")], "trigonometry", [OS_PRECALC]),
    ("us-precalculus-vectors", "traditional", "Precalculus", "Vectors",
     ["component form", "magnitude and direction", "vector operations", "dot product", "projections", "applications"],
     [("数学C ベクトル", "most")], "vectors", [OS_PRECALC]),
    ("us-precalculus-polar-and-complex", "traditional", "Precalculus", "Polar coordinates, complex numbers, and parametric equations",
     ["polar coordinates", "polar graphs", "trigonometric form of complex numbers", "De Moivre's theorem", "parametric equations"],
     [("数学C 平面上の曲線と複素数平面", "most")], "complex-numbers", [OS_PRECALC]),
    ("us-precalculus-conics", "traditional", "Precalculus", "Conic sections",
     ["parabolas", "ellipses", "hyperbolas", "rotated conics", "conics in polar coordinates"],
     [("数学C 平面上の曲線と複素数平面", "most")], "geometry", [OS_PRECALC]),
    ("us-precalculus-matrices-and-systems", "traditional", "Precalculus", "Systems and matrices",
     ["systems of three equations", "Gaussian elimination", "matrix operations", "inverses", "determinants and Cramer's rule", "linear programming"],
     [("数学C 数学的な表現の工夫", "some", "行列"), ("数学II 図形と方程式", "some", "線形計画法")], "linear-algebra", [OS_PRECALC]),
    ("us-precalculus-sequences-and-induction", "traditional", "Precalculus", "Sequences, series, and induction",
     ["sequences", "series", "mathematical induction", "binomial theorem", "counting principles"],
     [("数学B 数列", "full"), ("数学II 式と証明", "some", "二項定理"), ("数学A 場合の数と確率", "some")], "sequences", [OS_PRECALC]),
    ("us-precalculus-limits", "traditional", "Precalculus", "Introduction to calculus",
     ["limits numerically and graphically", "limit laws", "continuity", "derivative as a limit"],
     [("数学II 微分の考え", "some"), ("数学III 極限", "some")], "calculus", [OS_PRECALC]),
    # ---------------- Integrated Math 1
    ("us-integrated-1-linear", "integrated", "Integrated Math 1", "Linear equations, inequalities, and functions",
     ["solving linear equations", "linear functions", "arithmetic sequences", "function notation"],
     [("中1 一次方程式", "most"), ("中2 一次関数", "full")], "algebra", [CCSS]),
    ("us-integrated-1-systems", "integrated", "Integrated Math 1", "Systems of equations and inequalities",
     ["solving systems", "systems of inequalities"],
     [("中2 連立方程式", "full")], "algebra", [CCSS]),
    ("us-integrated-1-exponential", "integrated", "Integrated Math 1", "Exponential functions",
     ["exponential growth and decay", "geometric sequences", "comparing linear and exponential"],
     [("数学II 指数関数と対数関数", "some")], "functions", [CCSS]),
    ("us-integrated-1-statistics", "integrated", "Integrated Math 1", "Statistics",
     ["one-variable data", "two-variable data", "two-way tables", "scatter plots"],
     [("中1 データの活用", "most"), ("中2 データの活用", "full"), ("数学I データの分析", "some")], "statistics", [CCSS]),
    ("us-integrated-1-congruence-and-transformations", "integrated", "Integrated Math 1", "Congruence and transformations",
     ["rigid motions", "congruence", "triangle congruence", "constructions"],
     [("中1 平面図形", "most"), ("中2 平行と合同", "most")], "geometry", [CCSS]),
    ("us-integrated-1-coordinate-geometry", "integrated", "Integrated Math 1", "Coordinate geometry",
     ["distance and midpoint", "slope", "parallel and perpendicular lines"],
     [("数学II 図形と方程式", "some")], "geometry", [CCSS]),
    # ---------------- Integrated Math 2
    ("us-integrated-2-quadratics", "integrated", "Integrated Math 2", "Quadratic functions and equations",
     ["graphing quadratics", "solving quadratics", "complex numbers", "systems with quadratics"],
     [("中3 二次方程式", "full"), ("中3 関数 y=ax²", "full"), ("数学I 二次関数", "most")], "functions", [CCSS]),
    ("us-integrated-2-polynomials-and-complex", "integrated", "Integrated Math 2", "Polynomials, radicals, and complex numbers",
     ["polynomial operations", "factoring", "radicals and rational exponents", "complex numbers"],
     [("中3 式の展開と因数分解", "full"), ("中3 平方根", "most"), ("数学II 複素数と方程式", "some")], "algebra", [CCSS]),
    ("us-integrated-2-similarity-and-trig", "integrated", "Integrated Math 2", "Similarity and right triangle trigonometry",
     ["dilations", "similar triangles", "Pythagorean theorem", "sine, cosine, tangent"],
     [("中3 相似な図形", "full"), ("中3 三平方の定理", "full"), ("数学I 図形と計量", "some")], "geometry", [CCSS]),
    ("us-integrated-2-circles", "integrated", "Integrated Math 2", "Circles and solids",
     ["inscribed angles", "arc length and sectors", "equation of a circle", "volume"],
     [("中3 円", "full"), ("中1 空間図形", "some")], "geometry", [CCSS]),
    ("us-integrated-2-probability", "integrated", "Integrated Math 2", "Probability",
     ["sample spaces", "independence", "conditional probability", "counting"],
     [("中2 確率", "full"), ("数学A 場合の数と確率", "most")], "probability", [CCSS]),
    # ---------------- Integrated Math 3
    ("us-integrated-3-polynomials", "integrated", "Integrated Math 3", "Polynomial functions",
     ["graphs of polynomials", "polynomial division", "remainder and factor theorems", "fundamental theorem of algebra"],
     [("数学II 複素数と方程式", "most"), ("数学II 式と証明", "some")], "algebra", [CCSS]),
    ("us-integrated-3-rational-and-radical", "integrated", "Integrated Math 3", "Rational and radical functions",
     ["rational expressions", "rational equations", "radical functions", "inverses"],
     [("数学II 式と証明", "most"), ("数学III 極限", "some")], "functions", [CCSS]),
    ("us-integrated-3-exponential-and-logarithmic", "integrated", "Integrated Math 3", "Exponential and logarithmic functions",
     ["logarithms", "exponential and logarithmic equations", "modeling"],
     [("数学II 指数関数と対数関数", "full")], "functions", [CCSS]),
    ("us-integrated-3-trigonometric-functions", "integrated", "Integrated Math 3", "Trigonometric functions",
     ["radians and the unit circle", "graphs of trig functions", "identities", "law of sines and cosines"],
     [("数学II 三角関数", "most"), ("数学I 図形と計量", "most")], "trigonometry", [CCSS]),
    ("us-integrated-3-inference", "integrated", "Integrated Math 3", "Statistics and inference",
     ["normal distribution", "sampling and experiments", "estimating population parameters", "simulation"],
     [("数学B 統計的な推測", "most"), ("数学I データの分析", "some")], "statistics", [CCSS]),
    ("us-integrated-3-geometric-modeling", "integrated", "Integrated Math 3", "Geometric modeling",
     ["cross sections", "density", "design problems"],
     [("中1 空間図形", "some")], "geometry", [CCSS]),
    # ---------------- AP Calculus AB (CED units 1-8)
    ("us-ap-calculus-ab-1-limits", "ap", "AP Calculus AB", "Unit 1: Limits and continuity",
     ["limit notation", "estimating limits from graphs and tables", "limit laws", "squeeze theorem", "types of discontinuities", "continuity", "limits at infinity", "intermediate value theorem"],
     [("数学III 極限", "most"), ("数学II 微分の考え", "some")], "analysis", [AP_CALC]),
    ("us-ap-calculus-ab-2-differentiation-basics", "ap", "AP Calculus AB", "Unit 2: Differentiation — definition and fundamental properties",
     ["average and instantaneous rate of change", "limit definition of the derivative", "differentiability", "power rule", "product and quotient rules", "derivatives of trig, exponential, and log functions"],
     [("数学II 微分の考え", "most"), ("数学III 微分法", "most")], "calculus", [AP_CALC]),
    ("us-ap-calculus-ab-3-differentiation-advanced", "ap", "AP Calculus AB", "Unit 3: Differentiation — composite, implicit, and inverse functions",
     ["chain rule", "implicit differentiation", "derivatives of inverse functions", "derivatives of inverse trig functions", "higher-order derivatives"],
     [("数学III 微分法", "most", "逆三角関数の微分は日本の高校範囲外")], "calculus", [AP_CALC]),
    ("us-ap-calculus-ab-4-contextual-applications", "ap", "AP Calculus AB", "Unit 4: Contextual applications of differentiation",
     ["rates of change in context", "rectilinear motion", "related rates", "linearization", "L'Hôpital's rule"],
     [("数学III 微分法", "some", "related rates と L'Hôpital は日本の高校では扱わない")], "calculus", [AP_CALC]),
    ("us-ap-calculus-ab-5-analytical-applications", "ap", "AP Calculus AB", "Unit 5: Analytical applications of differentiation",
     ["mean value theorem", "extreme value theorem", "critical points", "first and second derivative tests", "concavity", "curve sketching", "optimization"],
     [("数学II 微分の考え", "most"), ("数学III 微分法", "full")], "calculus", [AP_CALC]),
    ("us-ap-calculus-ab-6-integration", "ap", "AP Calculus AB", "Unit 6: Integration and accumulation of change",
     ["accumulation", "Riemann sums", "definite integral", "fundamental theorem of calculus", "antiderivatives", "u-substitution", "integration by completing the square"],
     [("数学II 積分の考え", "most"), ("数学III 積分法", "most")], "calculus", [AP_CALC]),
    ("us-ap-calculus-ab-7-differential-equations", "ap", "AP Calculus AB", "Unit 7: Differential equations",
     ["modeling with differential equations", "slope fields", "separation of variables", "exponential models"],
     [("数学III 積分法", "some", "変数分離形は一部の教科書のみ")], "calculus", [AP_CALC]),
    ("us-ap-calculus-ab-8-applications-of-integration", "ap", "AP Calculus AB", "Unit 8: Applications of integration",
     ["average value of a function", "motion problems", "area between curves", "volumes by cross sections", "disk and washer methods"],
     [("数学III 積分法", "most", "関数の平均値は日本の高校範囲外")], "calculus", [AP_CALC]),
    # ---------------- AP Calculus BC (BC-only units)
    ("us-ap-calculus-bc-6-integration-techniques", "ap", "AP Calculus BC", "Units 6–8 (BC only): Integration by parts, partial fractions, improper integrals, Euler's method, logistic models, arc length",
     ["integration by parts", "partial fractions", "improper integrals", "Euler's method", "logistic differential equations", "arc length"],
     [("数学III 積分法", "most", "部分積分・部分分数・曲線の長さは数III。広義積分・Euler 法・ロジスティックは範囲外")], "calculus", [AP_CALC]),
    ("us-ap-calculus-bc-9-parametric-polar-vector", "ap", "AP Calculus BC", "Unit 9: Parametric equations, polar coordinates, and vector-valued functions",
     ["derivatives of parametric equations", "arc length of parametric curves", "vector-valued functions", "polar derivatives", "area in polar coordinates"],
     [("数学C 平面上の曲線と複素数平面", "some", "媒介変数・極座標の定義のみ"), ("数学III 微分法", "some")], "calculus", [AP_CALC]),
    ("us-ap-calculus-bc-10-series", "ap", "AP Calculus BC", "Unit 10: Infinite sequences and series",
     ["convergence tests", "geometric and p-series", "alternating series", "ratio test", "absolute and conditional convergence", "Taylor polynomials", "power series", "radius of convergence", "Taylor and Maclaurin series"],
     [("数学III 極限", "some", "無限等比級数のみ。収束判定・Taylor 級数は日本の高校範囲外")], "analysis", [AP_CALC]),
    # ---------------- AP Statistics (CED units 1-9)
    ("us-ap-statistics-1-one-variable", "ap", "AP Statistics", "Unit 1: Exploring one-variable data",
     ["categorical and quantitative variables", "graphs for one variable", "measures of center and spread", "boxplots and outliers", "normal distribution and z-scores"],
     [("数学I データの分析", "most"), ("数学B 統計的な推測", "some")], "statistics", [AP_STAT]),
    ("us-ap-statistics-2-two-variable", "ap", "AP Statistics", "Unit 2: Exploring two-variable data",
     ["two-way tables", "scatter plots", "correlation", "least-squares regression", "residuals", "transformations"],
     [("数学I データの分析", "most"), ("数学B 数学と社会生活", "some")], "statistics", [AP_STAT]),
    ("us-ap-statistics-3-collecting-data", "ap", "AP Statistics", "Unit 3: Collecting data",
     ["sampling methods", "bias", "experiments vs. observational studies", "randomization and blocking"],
     [("中3 標本調査", "some"), ("数学B 統計的な推測", "some")], "statistics", [AP_STAT]),
    ("us-ap-statistics-4-probability", "ap", "AP Statistics", "Unit 4: Probability, random variables, and probability distributions",
     ["probability rules", "conditional probability and independence", "random variables", "binomial and geometric distributions"],
     [("数学A 場合の数と確率", "most"), ("数学B 統計的な推測", "most")], "probability", [AP_STAT]),
    ("us-ap-statistics-5-sampling-distributions", "ap", "AP Statistics", "Unit 5: Sampling distributions",
     ["sampling distribution of a proportion", "sampling distribution of a mean", "central limit theorem"],
     [("数学B 統計的な推測", "most")], "statistics", [AP_STAT]),
    ("us-ap-statistics-6-proportions", "ap", "AP Statistics", "Unit 6: Inference for categorical data — proportions",
     ["confidence intervals for proportions", "significance tests for proportions", "Type I and Type II errors", "power"],
     [("数学B 統計的な推測", "most")], "statistics", [AP_STAT]),
    ("us-ap-statistics-7-means", "ap", "AP Statistics", "Unit 7: Inference for quantitative data — means",
     ["t-distribution", "confidence intervals for means", "one-sample and two-sample t-tests", "paired data"],
     [("数学B 統計的な推測", "some", "t 分布は日本の高校範囲外")], "statistics", [AP_STAT]),
    ("us-ap-statistics-8-chi-square", "ap", "AP Statistics", "Unit 8: Inference for categorical data — chi-square",
     ["goodness-of-fit", "test for independence", "test for homogeneity"],
     [("数学B 統計的な推測", "none", "日本の高校範囲外")], "statistics", [AP_STAT]),
    ("us-ap-statistics-9-slopes", "ap", "AP Statistics", "Unit 9: Inference for quantitative data — slopes",
     ["confidence interval for the slope", "t-test for the slope"],
     [("数学B 統計的な推測", "none", "日本の高校範囲外")], "statistics", [AP_STAT]),
    # ---------------- Calculus I (OpenStax Vol 1)
    ("us-calculus-1-functions", "college", "Calculus I", "Functions and graphs",
     ["review of functions", "basic classes of functions", "trigonometric functions", "inverse functions", "exponential and logarithmic functions", "hyperbolic functions"],
     [("数学II 三角関数", "most"), ("数学II 指数関数と対数関数", "most"), ("数学III 極限", "some", "逆関数・合成関数")], "functions", [OS_CALC1]),
    ("us-calculus-1-limits", "college", "Calculus I", "Limits",
     ["limit of a function", "limit laws", "continuity", "precise definition of a limit"],
     [("数学III 極限", "most", "ε-δ は日本の高校範囲外")], "analysis", [OS_CALC1]),
    ("us-calculus-1-derivatives", "college", "Calculus I", "Derivatives",
     ["definition of the derivative", "differentiation rules", "derivatives as rates of change", "trigonometric derivatives", "chain rule", "implicit differentiation", "exponential and logarithmic derivatives"],
     [("数学II 微分の考え", "most"), ("数学III 微分法", "full")], "calculus", [OS_CALC1]),
    ("us-calculus-1-applications-of-derivatives", "college", "Calculus I", "Applications of derivatives",
     ["related rates", "linear approximations", "maxima and minima", "mean value theorem", "derivatives and the shape of a graph", "limits at infinity and asymptotes", "optimization", "L'Hôpital's rule", "Newton's method", "antiderivatives"],
     [("数学III 微分法", "most", "related rates・Newton 法・L'Hôpital は日本の高校範囲外")], "calculus", [OS_CALC1]),
    ("us-calculus-1-integration", "college", "Calculus I", "Integration",
     ["approximating areas", "definite integral", "fundamental theorem of calculus", "integration formulas and net change", "substitution", "integrals of exponential, logarithmic, and inverse trig functions"],
     [("数学II 積分の考え", "full"), ("数学III 積分法", "most")], "calculus", [OS_CALC1]),
    ("us-calculus-1-applications-of-integration", "college", "Calculus I", "Applications of integration",
     ["area between curves", "volumes by slicing", "volumes of revolution (disk, washer, shell)", "arc length and surface area", "physical applications", "exponential growth and decay"],
     [("数学III 積分法", "most", "shell method と回転面の面積は日本の高校範囲外")], "calculus", [OS_CALC1]),
    # ---------------- Calculus II (OpenStax Vol 2)
    ("us-calculus-2-applications-of-integration", "college", "Calculus II", "Applications of integration",
     ["area between curves", "volumes", "arc length", "physical applications (work, hydrostatic force)", "moments and centers of mass"],
     [("数学III 積分法", "most", "仕事・重心は日本の高校範囲外")], "calculus", [OS_CALC2]),
    ("us-calculus-2-techniques-of-integration", "college", "Calculus II", "Techniques of integration",
     ["integration by parts", "trigonometric integrals", "trigonometric substitution", "partial fractions", "numerical integration", "improper integrals"],
     [("数学III 積分法", "most", "広義積分・数値積分は日本の高校範囲外")], "calculus", [OS_CALC2]),
    ("us-calculus-2-differential-equations", "college", "Calculus II", "Introduction to differential equations",
     ["basics of differential equations", "direction fields", "separable equations", "logistic equation", "first-order linear equations"],
     [("数学III 積分法", "some", "変数分離形のみ")], "calculus", [OS_CALC2]),
    ("us-calculus-2-sequences-and-series", "college", "Calculus II", "Sequences and series",
     ["sequences", "infinite series", "divergence and integral tests", "comparison tests", "alternating series", "ratio and root tests"],
     [("数学III 極限", "some", "無限等比級数のみ。収束判定は日本の高校範囲外"), ("数学B 数列", "some")], "analysis", [OS_CALC2]),
    ("us-calculus-2-power-series", "college", "Calculus II", "Power series",
     ["power series and functions", "properties of power series", "Taylor and Maclaurin series", "working with Taylor series"],
     [("数学III 極限", "none", "日本の高校範囲外")], "analysis", [OS_CALC2]),
    ("us-calculus-2-parametric-and-polar", "college", "Calculus II", "Parametric equations and polar coordinates",
     ["parametric equations", "calculus of parametric curves", "polar coordinates", "area and arc length in polar coordinates", "conic sections"],
     [("数学C 平面上の曲線と複素数平面", "most"), ("数学III 微分法", "some")], "calculus", [OS_CALC2]),
    # ---------------- Calculus III (OpenStax Vol 3)
    ("us-calculus-3-vectors-in-space", "college", "Calculus III", "Vectors in space",
     ["vectors in the plane and in space", "dot product", "cross product", "equations of lines and planes", "quadric surfaces", "cylindrical and spherical coordinates"],
     [("数学C ベクトル", "most", "外積・二次曲面は日本の高校範囲外")], "vectors", [OS_CALC3]),
    ("us-calculus-3-vector-valued-functions", "college", "Calculus III", "Vector-valued functions",
     ["vector-valued functions and space curves", "calculus of vector-valued functions", "arc length and curvature", "motion in space"],
     [("数学C ベクトル", "some"), ("数学III 微分法", "some", "速度・加速度")], "calculus", [OS_CALC3]),
    ("us-calculus-3-partial-derivatives", "college", "Calculus III", "Differentiation of functions of several variables",
     ["functions of several variables", "limits and continuity", "partial derivatives", "tangent planes and linear approximations", "chain rule", "directional derivatives and the gradient", "maxima and minima", "Lagrange multipliers"],
     [("数学III 微分法", "none", "日本の高校範囲外（大学 1 年の微積）")], "calculus", [OS_CALC3]),
    ("us-calculus-3-multiple-integrals", "college", "Calculus III", "Multiple integration",
     ["double integrals", "double integrals in polar coordinates", "triple integrals", "cylindrical and spherical coordinates", "change of variables"],
     [("数学III 積分法", "none", "日本の高校範囲外")], "calculus", [OS_CALC3]),
    ("us-calculus-3-vector-calculus", "college", "Calculus III", "Vector calculus",
     ["vector fields", "line integrals", "conservative vector fields", "Green's theorem", "divergence and curl", "surface integrals", "Stokes' theorem", "divergence theorem"],
     [("数学C ベクトル", "none", "日本の高校範囲外")], "calculus", [OS_CALC3]),
    # ---------------- Linear Algebra
    ("us-linear-algebra-systems-and-matrices", "college", "Linear Algebra", "Systems of linear equations and matrices",
     ["row reduction and echelon forms", "vector equations", "matrix equation Ax = b", "solution sets", "linear independence", "matrix operations", "inverse of a matrix"],
     [("数学C 数学的な表現の工夫", "some", "行列の基礎"), ("中2 連立方程式", "some")], "linear-algebra", [LAY]),
    ("us-linear-algebra-determinants", "college", "Linear Algebra", "Determinants",
     ["cofactor expansion", "properties of determinants", "Cramer's rule", "determinants as area and volume"],
     [("数学C 数学的な表現の工夫", "some")], "linear-algebra", [LAY]),
    ("us-linear-algebra-vector-spaces", "college", "Linear Algebra", "Vector spaces",
     ["vector spaces and subspaces", "null space and column space", "bases", "coordinate systems", "dimension and rank", "change of basis"],
     [("数学C ベクトル", "some", "一次独立・一次結合のみ")], "linear-algebra", [LAY]),
    ("us-linear-algebra-linear-transformations", "college", "Linear Algebra", "Linear transformations",
     ["linear transformations", "matrix of a linear transformation", "kernel and range", "one-to-one and onto", "isomorphisms"],
     [("数学C 数学的な表現の工夫", "some", "一次変換")], "linear-algebra", [LAY]),
    ("us-linear-algebra-eigenvalues", "college", "Linear Algebra", "Eigenvalues and eigenvectors",
     ["eigenvectors and eigenvalues", "characteristic equation", "diagonalization", "complex eigenvalues", "applications to dynamical systems and Markov chains"],
     [("数学C 数学的な表現の工夫", "none", "日本の高校範囲外")], "linear-algebra", [LAY]),
    ("us-linear-algebra-orthogonality", "college", "Linear Algebra", "Orthogonality and least squares",
     ["inner product, length, orthogonality", "orthogonal sets and projections", "Gram–Schmidt process", "least-squares problems", "diagonalization of symmetric matrices", "quadratic forms", "singular value decomposition"],
     [("数学C ベクトル", "some", "内積・正射影のみ")], "linear-algebra", [LAY]),
    # ---------------- Intro Statistics (OpenStax)
    ("us-intro-statistics-sampling-and-data", "college", "Intro Statistics", "Sampling and data",
     ["definitions of statistics, probability, and key terms", "data, sampling, and variation", "levels of measurement", "frequency tables", "experimental design"],
     [("中3 標本調査", "most"), ("数学I データの分析", "some")], "statistics", [OS_STAT]),
    ("us-intro-statistics-descriptive-statistics", "college", "Intro Statistics", "Descriptive statistics",
     ["stem-and-leaf, line, and bar graphs", "histograms and box plots", "measures of location", "measures of center", "skewness", "measures of spread"],
     [("数学I データの分析", "full"), ("中2 データの活用", "full")], "statistics", [OS_STAT]),
    ("us-intro-statistics-probability", "college", "Intro Statistics", "Probability topics",
     ["terminology", "independent and mutually exclusive events", "two basic rules of probability", "contingency tables", "tree and Venn diagrams"],
     [("数学A 場合の数と確率", "most")], "probability", [OS_STAT]),
    ("us-intro-statistics-discrete-distributions", "college", "Intro Statistics", "Discrete random variables",
     ["probability distribution function", "mean and expected value", "binomial distribution", "geometric distribution", "hypergeometric distribution", "Poisson distribution"],
     [("数学B 統計的な推測", "most", "幾何・超幾何・Poisson は日本の高校範囲外")], "probability", [OS_STAT]),
    ("us-intro-statistics-continuous-distributions", "college", "Intro Statistics", "Continuous random variables and the normal distribution",
     ["continuous probability functions", "uniform distribution", "exponential distribution", "standard normal distribution", "using the normal distribution", "central limit theorem"],
     [("数学B 統計的な推測", "most")], "statistics", [OS_STAT]),
    ("us-intro-statistics-confidence-intervals", "college", "Intro Statistics", "Confidence intervals",
     ["single population mean (σ known / unknown)", "population proportion", "Student's t-distribution"],
     [("数学B 統計的な推測", "most")], "statistics", [OS_STAT]),
    ("us-intro-statistics-hypothesis-testing", "college", "Intro Statistics", "Hypothesis testing",
     ["null and alternative hypotheses", "Type I and II errors", "distribution needed for a test", "rare events, p-values", "two-sample tests", "matched pairs", "chi-square tests", "ANOVA"],
     [("数学B 統計的な推測", "most", "2 標本・χ²・ANOVA は日本の高校範囲外")], "statistics", [OS_STAT]),
    ("us-intro-statistics-regression", "college", "Intro Statistics", "Linear regression and correlation",
     ["linear equations", "scatter plots", "regression equation", "testing the significance of the correlation coefficient", "prediction", "outliers"],
     [("数学I データの分析", "most"), ("数学B 数学と社会生活", "some")], "statistics", [OS_STAT]),
    # ---------------- Discrete Math (Rosen)
    ("us-discrete-math-logic-and-proofs", "college", "Discrete Math", "Logic and proofs",
     ["propositional logic", "predicates and quantifiers", "rules of inference", "introduction to proofs", "proof methods and strategy"],
     [("数学I 集合と命題", "most", "命題・対偶・背理法")], "logic", [ROSEN]),
    ("us-discrete-math-sets-and-functions", "college", "Discrete Math", "Sets, functions, and sequences",
     ["sets and set operations", "functions", "sequences and summations", "cardinality"],
     [("数学I 集合と命題", "most"), ("数学B 数列", "some")], "set-theory", [ROSEN]),
    ("us-discrete-math-number-theory", "college", "Discrete Math", "Number theory",
     ["divisibility and modular arithmetic", "integer representations", "primes and GCD", "solving congruences", "applications to cryptography"],
     [("数学A 数学と人間の活動", "most")], "number-theory", [ROSEN]),
    ("us-discrete-math-induction-and-recursion", "college", "Discrete Math", "Induction and recursion",
     ["mathematical induction", "strong induction and well-ordering", "recursive definitions", "recursive algorithms"],
     [("数学B 数列", "most", "数学的帰納法・漸化式")], "proof", [ROSEN]),
    ("us-discrete-math-counting", "college", "Discrete Math", "Counting",
     ["basics of counting", "pigeonhole principle", "permutations and combinations", "binomial coefficients", "generalized permutations and combinations", "generating functions", "inclusion–exclusion"],
     [("数学A 場合の数と確率", "most")], "combinatorics", [ROSEN]),
    ("us-discrete-math-discrete-probability", "college", "Discrete Math", "Discrete probability",
     ["probability theory", "Bayes' theorem", "expected value and variance"],
     [("数学A 場合の数と確率", "most"), ("数学B 統計的な推測", "some")], "probability", [ROSEN]),
    ("us-discrete-math-graphs-and-relations", "college", "Discrete Math", "Relations, graphs, and trees",
     ["relations and their properties", "equivalence relations", "partial orderings", "graphs and graph models", "connectivity", "Euler and Hamilton paths", "shortest-path problems", "trees"],
     [("数学C 数学的な表現の工夫", "some", "離散グラフ")], "discrete", [ROSEN]),
]

# 数学C の単元ではないが jp_equivalents で参照する小学校の範囲（JSON は作らない）
ELEMENTARY = {"小学校 分数・小数", "小学校 割合"}
