"""Decisions applied by fix_phase1.py to the Phase 1 ledger.

Each table is a human judgement, one line per row, so a reviewer can disagree
with a single line. Why the tables exist: docs/DECISIONS.md, "Phase 1 修正".
"""

# ---------------------------------------------------------------- 1. review 30
# Phase 1 report, "対応が怪しい語 30": all approved as proposed (2026-09-23).
# Additions from the review: 4 directly proportional, 17 relative maximum,
# 9 / 20 keep the written form as a variant.
# id -> fields to set. en_alt / en_variants / ja_alt are appended, not replaced.
REVIEW30 = {
    "vertex-form": {},
    "standard-form": {},
    "domain-and-range": {},
    "direct-proportion": {"en": "direct variation", "en_alt": ["direct proportion"],
                          "en_variants": [("directly proportional", "both")]},
    "proportion": {},
    "equation": {"ja_alt": ["等式"]},  # 6: 等式 / 方程式 folded (see MERGES)
    "polynomial": {"ja_alt": ["整式"]},  # 7
    "proposition": {"en": "statement", "en_alt": ["proposition"], "mapping": "near"},
    "necessary-and-sufficient-condition": {
        "en": "if and only if", "en_variants": [("necessary and sufficient condition", "written")]},
    "trigonometric-ratio": {"mapping": "near"},
    "terminal-side": {},
    "auxiliary-angle-form": {},
    "angle-addition-formulas": {"en": "sum and difference formulas", "en_alt": ["angle addition formulas"]},
    "trigonometric-inequality": {"mapping": "near"},
    "argument": {"en": "argument (of a logarithm)"},
    "derivative-at-a-point": {},
    "local-maximum": {"mapping": "near", "en_variants": [("relative maximum", "both")]},
    "opens-downward": {"en": "concave down", "en_alt": ["opens downward"]},
    "riemann-sum": {},
    "integration-by-substitution": {"en": "u-substitution",
                                    "en_variants": [("substitution", "written")]},
    "antiderivative": {"mapping": "near"},
    "point-of-internal-division": {"en": "point that divides the segment internally"},
    "the-five-centers-of-a-triangle": {"en": "points of concurrency"},
    "power-of-a-point": {},
    "tangent-chord-theorem": {"en": "tangent-chord angle"},
    "counting": {},
    "repeated-trials": {"en": "Bernoulli trials", "en_alt": ["binomial setting"]},
    "standard-score": {},
    "sequence-of-differences": {"en": "first differences"},
    "base-case": {},
}

# ------------------------------------------------------------- 3. merges/renames
# (from, into, main). main="from" makes the merged-away row's ja the headword
# and moves the surviving row's ja to ja_alt. Applied in order.
MERGES = [
    ("equation-houteishiki", "equation", "from"),
    ("variable-hanpirei", "variable", "from"),
    ("multiply-insuubunkai", "multiply", "into"),
    ("simplify-heihoukon", "simplify", "from"),
    ("simplify-equations", "simplify", "into"),
    ("pythagorean-theorem-alt", "pythagorean-theorem", "into"),
    ("polynomial-shiki", "polynomial", "into"),
    ("factor-out-the-common-factor-shiki", "factor-out-the-common-factor", "into"),
    ("element-alt", "element", "into"),
    ("x-intercept-kansuu", "x-intercept", "into"),
    ("x-intercept-functions", "x-intercept", "into"),
    ("sine-katakana", "sine", "into"),
    ("cosine-katakana", "cosine", "into"),
    ("tangent-katakana", "tangent", "into"),
    ("find-the-angle-keiryou", "find-the-angle", "into"),
    ("find-the-angle-seishitsu", "find-the-angle", "into"),
    ("measure-of-center-bunseki", "measure-of-center", "into"),
    ("angle-bisector-theorem-seishitsu", "angle-bisector-theorem", "from"),
    ("coordinates-katsudou", "coordinates", "into"),
    ("expansion-shoumei", "expansion", "into"),
    ("compare-shoumei", "compare", "into"),
    ("compare-coefficients-shoumei", "compare-coefficients", "into"),
    ("midpoint-houteishiki", "midpoint", "into"),
    ("centroid-houteishiki", "centroid", "into"),
    ("equation-of-a-line-houteishiki", "equation-of-a-line", "into"),
    ("parallel-lines-houteishiki", "parallel-lines", "into"),
    ("find-the-equation-houteishiki", "find-the-equation", "into"),
    ("intersect-houteishiki", "intersect", "into"),
    ("trigonometric-identities-kansuu", "trigonometric-identities", "into"),
    ("solve-for-theta-kansuu", "solve-for-theta", "into"),
    ("increasing-taisuu", "increasing", "into"),
    ("decreasing-taisuu", "decreasing", "into"),
    ("limit-kangae", "limit", "into"),
    ("local-maximum-alt", "local-maximum", "into"),
    ("local-minimum-alt", "local-minimum", "into"),
    ("rate-of-change-kangae", "rate-of-change", "into"),
    ("point-of-tangency-kangae", "point-of-tangency", "into"),
    ("geometric-mean-similarity", "geometric-mean", "into"),
    ("mean-suisoku", "mean", "into"),
    ("population-mean-suisoku", "population-mean", "from"),
    ("optimization-seikatsu", "optimization", "into"),
    ("parameter-bibun", "parameter", "from"),
    ("arc-length-circles", "arc-length", "into"),
    ("substitute-sekibun", "substitute", "into"),
    ("nth-root-heimen", "nth-root", "into"),
    ("rotation-heimen", "rotation", "into"),
    ("sketch-the-curve-heimen", "sketch-the-curve", "into"),
    ("distribute-equations", "distribute", "into"),
    ("evaluate-equations", "evaluate", "into"),
    ("solution-set-equations", "solution-set", "into"),
    ("function-notation-functions", "function-notation", "into"),
    ("domain-and-range-functions", "domain-and-range", "into"),
    ("arithmetic-sequence-functions", "arithmetic-sequence", "into"),
    ("geometric-sequence-functions", "geometric-sequence", "into"),
    ("perfect-square-trinomial-factoring", "perfect-square-trinomial", "into"),
    ("zero-product-property-factoring", "zero-product-property", "into"),
    ("leading-coefficient-factoring", "leading-coefficient", "into"),
    ("vertex-form-quadratics", "vertex-form", "into"),
    ("axis-of-symmetry-quadratics", "axis-of-symmetry", "into"),
    ("prove-proof", "prove", "into"),
    ("inverse-proof", "inverse", "into"),
    ("isosceles-triangle-triangles", "isosceles-triangle", "into"),
    ("ratio-of-areas-of-similar-figures-similarity", "ratio-of-areas-of-similar-figures", "into"),
    ("inscribed-angle-circles", "inscribed-angle", "into"),
    ("area-of-a-sector-circles", "area-of-a-sector", "into"),
    ("slant-height-volume", "slant-height", "into"),
    ("reflection-transformations", "reflection", "into"),
    ("complex-conjugate-numbers", "complex-conjugate", "into"),
    ("remainder-theorem-polynomials", "remainder-theorem", "into"),
    ("rational-function-functions", "rational-function", "into"),
    ("complex-fraction-functions", "complex-fraction", "into"),
    ("rational-exponent-functions", "rational-exponent", "into"),
    ("radical-function-functions", "radical-function", "into"),
    ("radical-equation-functions", "radical-equation", "from"),
    ("infinite-geometric-series-series", "infinite-geometric-series", "into"),
    ("z-score-statistics", "z-score", "into"),
    ("average-rate-of-change-functions", "average-rate-of-change", "into"),
    ("composition-of-transformations-functions", "composition-of-transformations", "into"),
    ("composition-linalg", "composition-of-transformations", "into"),
    ("absolute-value-equation-functions", "absolute-value-equation", "into"),
    ("double-angle-formulas-trigonometry", "double-angle-formulas", "into"),
    ("half-angle-formulas-trigonometry", "half-angle-formulas", "into"),
    ("component-form-vectors", "component-form", "into"),
    ("dot-product-vectors", "dot-product", "into"),
    ("parametric-equations-complex", "parametric-equations", "into"),
    ("base-case-induction", "base-case", "into"),
    ("squeeze-theorem-limits", "squeeze-theorem", "into"),
    ("removable-discontinuity-limits", "removable-discontinuity", "into"),
    ("power-rule-basics", "power-rule", "into"),
    ("chain-rule-advanced", "chain-rule", "into"),
    ("implicit-differentiation-advanced", "implicit-differentiation", "into"),
    ("linearization-applications", "linearization", "into"),
    ("extreme-value-theorem-applications", "extreme-value-theorem", "into"),
    ("critical-point-applications", "critical-point", "from"),
    ("first-derivative-test-applications", "first-derivative-test", "into"),
    ("absolute-extrema-applications", "absolute-extrema", "into"),
    ("concavity-applications", "concavity", "into"),
    ("riemann-sum-integration", "riemann-sum", "into"),
    ("fundamental-theorem-of-calculus-integration", "fundamental-theorem-of-calculus", "from"),
    ("function-defined-by-an-integral-integration", "function-defined-by-an-integral", "into"),
    ("integration-by-parts-techniques", "integration-by-parts", "into"),
    ("extrapolation-variable", "extrapolation", "into"),
    ("properties-of-logarithms-functions", "properties-of-logarithms", "into"),
    ("logarithmic-differentiation-derivatives", "logarithmic-differentiation", "into"),
    ("summation-notation-integration", "summation-notation", "into"),
    ("linear-transformation-transformations", "linear-transformation", "into"),
    ("one-to-one-transformations", "one-to-one", "into"),
    ("sample-space-probability", "sample-space", "into"),
    ("point-estimate-intervals", "point-estimate", "into"),
    ("proof-by-contradiction-proofs", "proof-by-contradiction", "into"),
    ("floor-function-functions", "floor-function", "into"),
    ("division-algorithm-theory", "division-algorithm", "into"),
    ("recursive-definition-recursion", "recursive-definition", "into"),
    # same concept, found while re-assigning mapping (no dedup suffix)
    ("direction-field", "slope-field", "from"),
    ("area-polar-calc2", "area-in-polar-coordinates", "into"),
    ("conics-in-polar-coordinates", "polar-equations-of-conics", "into"),
    ("stem-and-leaf-stats", "stem-and-leaf-plot", "into"),
    ("inclusion-exclusion", "inclusion-exclusion-principle", "into"),
    ("related-rates-calc1", "related-rates", "into"),
    ("trapezoidal-sum", "trapezoidal-rule", "from"),
    ("end-behavior-alg2", "end-behavior", "into"),
    ("reference-angle-alg2", "reference-angle", "into"),
    ("orthogonal-projection-linalg", "orthogonal-projection", "into"),
    # became duplicates when the review-30 English was applied
    ("sum-and-difference-formulas", "angle-addition-formulas", "into"),
    ("u-substitution", "integration-by-substitution", "into"),
]

# Merges that need the target renamed first (arc length of a curve is not the
# arc of a circle; 置き換える must free the id "substitute" for 代入する).
MERGES_AFTER_RENAME = [
    ("arc-length-integration", "arc-length-of-a-curve", "into"),
]

# old id -> new id (and optional field overrides). Same English, different
# concept: these stay separate entries under ids that say what they are.
RENAMES = [
    ("distance", "distance-traveled", {}),
    ("distance-zukei", "distance", {}),
    ("base-zukei", "base-of-a-solid", {}),
    ("base-shikakkei", "base-of-a-triangle", {}),
    ("cube-zukei", "cube-solid", {}),
    ("less-than-suu", "strictly-less-than", {}),
    ("solve-for", "solve-instruction", {}),
    ("solve-for-keisan", "solve-for", {}),
    ("divisor-keisan", "divisor-in-division", {}),
    ("substitution-houteishiki", "substitution-method", {"en": "substitution method"}),
    ("substitution-shiki", "substitution-new-variable", {}),
    ("range", "range-of-data", {}),
    ("range-kansuu", "range", {}),
    ("corresponding-angles-goudou", "corresponding-angles-of-congruent-figures", {}),
    ("square-shikakkei", "square-shape", {}),
    ("square-heihoukon", "square-a-number", {}),
    ("opposite-shikakkei", "opposite-facing", {}),
    ("factor-insuubunkai", "factor-an-expression", {}),
    ("group", "group-into-classes", {}),
    ("group-insuubunkai", "group-terms", {}),
    ("estimate", "bound-estimate", {}),
    ("estimate-chousa", "estimate", {}),
    ("intersection", "point-of-intersection", {"en": "point of intersection"}),
    ("intersection-meidai", "intersection", {}),
    ("hypothesis-bunseki", "statistical-hypothesis", {}),
    ("variable-bunseki", "statistical-variable", {}),
    ("complement-kakuritsu", "complementary-event", {"en": "complement (of an event)"}),
    ("addition-rule", "addition-principle", {}),
    ("addition-rule-kakuritsu", "addition-rule", {}),
    ("multiplication-rule", "multiplication-principle", {}),
    ("multiplication-rule-kakuritsu", "multiplication-rule", {}),
    ("median-seishitsu", "median-of-a-triangle", {}),
    ("congruence-katsudou", "congruence-modulo-n", {}),
    ("decimal-katsudou", "decimal-system", {}),
    ("sketch", "sketch-of-a-solid", {}),
    ("sketch-houteishiki", "sketch", {}),
    ("arithmetic-mean-suuretsu", "arithmetic-middle-term", {}),
    ("geometric-mean-suuretsu", "geometric-middle-term", {}),
    ("approximation", "approximate-number", {}),
    ("approximation-seikatsu", "approximation", {}),
    ("arc-length-sekibun", "arc-length-of-a-curve", {}),
    ("modulus-heimen", "modulus-of-a-complex-number", {}),
    ("argument-heimen", "argument-of-a-complex-number", {}),
    ("edge-kufuu", "edge-of-a-graph", {}),
    ("path-kufuu", "path-in-a-graph", {}),
    ("find-the-inverse-kufuu", "find-the-inverse-matrix", {}),
    ("graph-hanpirei", "draw-a-graph", {}),
    ("graph-kufuu", "graph-network", {}),
    ("secant", "secant-line", {}),
    ("secant-trigonometry", "secant", {}),
    ("power-proportions", "statistical-power", {}),
    ("implicit-function-derivatives", "implicit-function-theorem", {"en": "implicit function theorem"}),
    ("survey-data", "questionnaire", {}),
    ("quadratic-form", "equation-in-quadratic-form", {"en": "equation in quadratic form"}),
    ("quadratic-form-linalg", "quadratic-form", {}),
    ("x", "parent-function", {"note": "y = x², y = |x|, y = √x など"}),
    # data/terms/ sample ids win (Phase 0): 代入する is "substitute", 移項する is
    # "move-term-to-other-side". 置き換える gives up "substitute".
    ("substitute", "substitute-new-variable", {}),
    ("plug-in", "substitute", {}),
    ("move-to-the-other-side", "move-term-to-other-side", {}),
]

# Headword fixes found while re-assigning mapping. ja becomes the established
# Japanese term; the old headword is kept in ja_alt unless it is wrong.
JA_FIX = {
    "undefined-terms": ("無定義用語", ["点・直線・平面"]),
    "del": ("ナブラ", ["デル"]),
    "levels-of-measurement": ("尺度水準", ["変数の種類"]),
    "glide-reflection": ("映進", ["グライド反射"]),
    "slope-field": ("方向場", []),  # 勾配場 is the gradient field; do not keep it
    "am-gm-inequality": (None, ["相加平均と相乗平均の関係"]),
    "shell-method": (None, ["バウムクーヘン積分"]),
    "invertible-matrix": (None, ["正則行列"]),
    "monotone-convergence-theorem": ("単調収束定理", ["単調数列定理"]),
    "trapezoidal-rule": (None, ["台形則"]),
    "mutually-exclusive": (None, ["排反"]),  # 〔用語・記号〕数学A
}

# ------------------------------------------------------ 2. Wikipedia verdicts
# The 210 rows whose langlink title differs from the provisional en.term.
# Everything not listed here is "記事名違いで問題なし" (same concept, the article
# is named differently or is the parent article that defines the term).
# Listed = a different concept: the langlink is dropped as a source.
WIKI_WRONG = {
    "algebraic-expression": "Polynomial は多項式。文字式は分数式も含む",
    "variable": "Writing system（文字体系）",
    "relationship": "Finitary relation は形式的な関係。中1 の「数量の関係」ではない",
    "plug-in": "Substitution (logic) は論理式の置換",
    "explain": "Explanation（数学外）",
    "set-up-a-system": "Coalition（連立政権）",
    "whisker": "Beard（髭）",
    "lottery": "Demarchy（くじ引き民主制）",
    "toss": "Throwing（投擲）",
    "estimate": "Evaluation（評価一般）",
    "braking-distance": "Brake（ブレーキ）",
    "scale-drawing": "Epitome (film)（映画「縮図」）",
    "draw-a-circle": "Igai ni Mango（楽曲）",
    "substitution-shiki": "Permutation（置換）",
    "bearing": "Cardinal direction（方位）は bearing ではない",
    "independent": "Independence（政治的独立）",
    "drawing-lots": "Demarchy（くじ引き民主制）",
    "centroid": "Center of mass は物理の質量中心。図形の重心は Centroid",
    "modulus": "Division (mathematics)。法（mod）ではない",
    "numerator": "Molecule（分子）",
    "terminal-side": "Radius（半径）",
    "trigonometric-inequality": "Triangle inequality（三角不等式 |a+b|≦|a|+|b|）",
    "local-maximum-alt": "Ordered set の極大元（maximal element）",
    "local-minimum-alt": "Ordered set の極小元（minimal element）",
    "common-difference": "Engineering tolerance（公差・工学）",
    "oscillate": "Oscillation（物理の振動）",
    "substitute-sekibun": "Permutation（置換）",
    "vector-equation": "System of linear equations は連立一次方程式",
    "cross-product": "Exterior algebra（外積代数）",
    "column": "Sequence（数列）。行列の列ではない",
    "elimination-method": "Process of elimination（消去法・推論）",
    "empirical-rule": "Rule of thumb（経験則一般）",
    "resultant": "Force（物理の力）",
    "limacon": "Caracole（騎兵戦術）",
    "power-rule-basics": "Power law（べき乗則・統計物理）",
    "axis-of-revolution": "Shaft (mechanical engineering)（機械の軸）",
    "explanatory-variable": "Expression (mathematics)（式）",
    "basis": "Base (topology)（開基）。線形代数の基底ではない",
    # found in the ja_check mismatch list (outside the 210)
    "base": "底 (初等幾何学) は図形の底。累乗の底（base of a power）ではない",
}

# ----------------------------------------------------------- 4. level_jp "—"
# The level a Japanese student meets the underlying content at. Content that is
# not in the Japanese school curriculum at all is 大学 (same rule as the US-side
# terms). Rows that leave the ledger are in OUT_OF_SCOPE instead.
LEVEL_JP = {
    "pemdas": "中1", "tick-mark": "中1", "literal-equation": "中2",
    "point-slope-form": "中2", "rise-over-run": "中2", "negative-reciprocal": "数II",
    "foil": "中3", "ac-method": "数I", "box-method": "中3", "area-model": "中3",
    "prime-polynomial": "中3", "like-radicals": "中3", "dot-plot": "中1",
    "stem-and-leaf-plot": "大学", "mean-absolute-deviation": "大学",
    "segment-addition-postulate": "中1", "angle-addition-postulate": "中1",
    "linear-pair": "中2", "two-column-proof": "中2", "paragraph-proof": "中2",
    "flowchart-proof": "中2", "statements-and-reasons": "中2", "ruler-postulate": "中1",
    "alternate-exterior-angles": "中2", "same-side-exterior-angles": "中2",
    "perpendicular-postulate": "中1", "cpctc": "中2", "sohcahtoa": "数I",
    "use-inverse-trig-to-find-the-angle": "数I", "intercepted-arc": "中3",
    "apothem": "中1", "glide-reflection": "大学", "coordinate-rule": "中1",
    "coordinate-proof": "数II", "horizontal-line-test": "数III",
    "vertical-line-test": "中1", "family-of-functions": "数I", "end-behavior": "数III",
    "key-features-of-a-graph": "数I", "quadratic-regression": "大学", "hole": "数III",
    "joint-variation": "大学", "exponential-regression": "大学",
    "reference-angle-alg2": "数II", "coterminal-angle": "数II", "midline": "数II",
    "empirical-rule": "数B", "test-point": "数I", "expanding-and-condensing-logs": "数II",
    "one-to-one-property": "数II", "ambiguous-case": "数I", "orientation": "数C",
    "inductive-step": "数B", "finding-limits-numerically": "数III",
    "representations-of-a-function": "中1", "linear-functions-in-context": "中2",
    "conditional-relative-frequency": "大学", "geometric-modeling": "数A",
    "corner-nondifferentiable": "数III", "outer-function": "数III",
    "inner-function": "数III", "units-of-a-rate-of-change": "数II",
    "candidates-test": "数II", "optimization-problem": "数II",
    "connecting-f-f-prime-and-f-double-prime": "数III", "accumulation": "数III",
    "accumulation-function": "数II", "net-change": "数III",
    "overestimate-and-underestimate": "数III", "disk-method": "数III",
    "washer-method": "数III", "liate": "数III", "shape-center-and-spread": "数I",
    "skewed-right": "中1", "outlier-rule": "数I", "resistant-statistic": "数I",
    "checking-conditions": "数B", "tangent-problem": "数II", "area-problem": "数II",
    "areas-and-distances": "数III",
}

# Rows that leave the ledger for ledger/out-of-scope.csv, with the reason.
OUT_OF_SCOPE = {
    "unit-rate": "小学校範囲（単位量あたりの大きさ・小5）。v1 は中1 から（PLAN 4）",
    "foot": "数学用語ではない（ヤード・ポンド法）。conventions の日米慣習差で扱う",
    "mile": "数学用語ではない（ヤード・ポンド法）。conventions の日米慣習差で扱う",
    "sales-tax": "数学用語ではない（米国の文章題の生活文脈）。conventions で扱う",
    "tip": "数学用語ではない（米国の文章題の生活文脈）。conventions で扱う",
}

# --------------------------------------------------------------- 1. mapping
# mapping is the quality of the word correspondence, not the curriculum level.
# US-side rows that were "none" because they are outside Japanese high school:
# an established Japanese term (固有値 = eigenvalue) is exact. Only the rows
# below differ from exact. near = a Japanese term exists but does not line up
# one to one; none = Japan has no name for it (the headword is descriptive).
MAPPING = {
    # Japan has no name for these US classroom devices / terms
    "pemdas": "none", "literal-equation": "none", "point-slope-form": "none",
    "rise-over-run": "none", "foil": "none", "ac-method": "none", "box-method": "none",
    "parent-function": "none", "segment-addition-postulate": "none",
    "angle-addition-postulate": "none", "two-column-proof": "none",
    "paragraph-proof": "none", "flowchart-proof": "none", "statements-and-reasons": "none",
    "ruler-postulate": "none", "perpendicular-postulate": "none", "cpctc": "none",
    "sohcahtoa": "none", "coordinate-rule": "none", "horizontal-line-test": "none",
    "vertical-line-test": "none", "end-behavior": "none", "joint-variation": "none",
"coterminal-angle": "none", "midline": "none",
    "test-point": "none", "expanding-and-condensing-logs": "none", "ambiguous-case": "none",
    "candidates-test": "none", "net-change": "none", "disk-method": "none",
    "washer-method": "none", "liate": "none", "net-change-theorem": "none",
    "telescoping-series": "none",
    # a Japanese term or phrase exists but covers it only partly
    "negative-reciprocal": "near", "area-model": "near", "prime-polynomial": "near",
    "like-radicals": "near", "same-side-exterior-angles": "near", "linear-pair": "near",
    "use-inverse-trig-to-find-the-angle": "near", "intercepted-arc": "near",
    "coordinate-proof": "near", "family-of-functions": "near",
    "key-features-of-a-graph": "near", "hole": "near", "empirical-rule": "near",
    "one-to-one-property": "near", "orientation": "near", "inductive-step": "near",
    "representations-of-a-function": "near", "linear-functions-in-context": "near",
    "geometric-modeling": "near", "corner-nondifferentiable": "near",
    "outer-function": "near", "inner-function": "near",
    "connecting-f-f-prime-and-f-double-prime": "near", "accumulation": "near",
    "accumulation-function": "near", "shape-center-and-spread": "near",
    "outlier-rule": "near", "resistant-statistic": "near", "checking-conditions": "near",
    "infinite-discontinuity": "near", "vertical-tangent": "near", "related-rates": "near",
    "integration-by-long-division": "near", "shell-method": "near",
    "nth-term-test": "near", "lagrange-error-bound": "near", "influential-point": "near",
    "voluntary-response-bias": "near", "types-of-functions": "near",
    "fundamental-theorem-of-calculus-part-1": "near",
    "fundamental-theorem-of-calculus-part-2": "near", "stars-and-bars": "near",
    # established Japanese term, same concept
    "tick-mark": "exact", "dot-plot": "exact", "stem-and-leaf-plot": "exact",
    "mean-absolute-deviation": "exact", "alternate-exterior-angles": "exact",
    "apothem": "exact", "glide-reflection": "exact", "quadratic-regression": "exact",
    "exponential-regression": "exact", "optimization-problem": "exact",
    "overestimate-and-underestimate": "exact", "skewed-right": "exact",
    "tangent-problem": "exact", "area-problem": "exact", "areas-and-distances": "exact",
    "finding-limits-numerically": "exact", "conditional-relative-frequency": "exact",
    "units-of-a-rate-of-change": "exact", "undefined-terms": "exact",
    "levels-of-measurement": "exact", "del": "exact",
}

# Level corrections made while re-assigning mapping (content is in Japanese
# school maths, so 大学 was wrong).
LEVEL_JP_FIX = {
    "parent-function": "数I",
    "net-change-theorem": "数II",
    "telescoping-series": "数B",
    "trigonometric-substitution": "数III",
}
